on: 
  push:
    branches:
      - main
name: 🚀 Deploy to Production on push
jobs:
  web-ui-build:
    name: 🎉 Deploy Web
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4

    - name: Install Dependencies
      run: npm i
    
    - name: Build Apps
      run: npm run build

  web-deploy:
    name: 🎉 Deploy App
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync App folder
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./app/
        server-dir: '/home/dbditsco/aksesgrosir.com/app/'

  resource-deploy:
    name: 🎉 Deploy Resource
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync Resource folder
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./resources/
        server-dir: '/home/dbditsco/aksesgrosir.com/resources/'

  public-deploy:
    name: 🎉 Deploy Public
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync Public folder
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./public/
        server-dir: '/home/dbditsco/aksesgrosir.com/public/'

  etc-deploy:
    name: 🎉 Deploy Etc
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync Etc files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: '/home/dbditsco/aksesgrosir.com/'
        exclude:  |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/app/**
          **/resources/**
          **/public/**
